config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root to: 'home#index'
	resources :secret_codes, only: [:index, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  belongs_to :user, optional: true
  attr_accessor :number_of_codes
  before_create :set_code

  self.per_page = 15 # pagination 15 records per page

  def set_code
    begin
      self.code = SecureRandom.hex(6)
    end while self.class.exists?(:code => code)
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :secret_code, autosave: true

  attr_accessor :code
  validates_presence_of	:code, on: :create
  validate :secret_code_validation, unless: -> { code.blank? }, on: :create

  private

  # Validate secret code and create association when valid
  def secret_code_validation
    secret_code = SecretCode.where("code = ? AND user_id IS NULL", code).first
    if secret_code.present?
      secret_code.user = self
    else
      errors.add(:base, "Invalid secret code")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to main_app.root_url, alert: exception.message }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :code])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  load_and_authorize_resource

  # List secret codes
  def index
    @secret_codes = SecretCode.includes(:user).paginate(:page => params[:page])
    @secret_code = SecretCode.new
  end

  # Generate new secret codes
  def create
    max_num = secret_code_params[:number_of_codes].to_i
    @secret_codes = (1..max_num).map { SecretCode.new }
    respond_to do |format|
      SecretCode.transaction do
        success = @secret_codes.map(&:save)
        if success.all?
          format.js
        else
          format.js
        end
      end
    end
  end

  private

  def secret_code_params
    params.require(:secret_code).permit(:number_of_codes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/home/index.html.erb
<div class="alert alert-primary" role="alert">
  <h1 class="text-center">This is a home page</h1>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">RubyAssignment</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    	<% if can? :read, SecretCode %>
	      <li class="nav-item <%= 'active' if request.original_url.include?('secret_codes')%>">
	      	<a class="nav-link" href="<%= secret_codes_path %>">Secret codes</a>
	      </li>
      <% end %>
    </ul>
    <span class="navbar-text">
      <%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render :partial => 'layouts/navbar' %>
    <% end %>
    <div class="alert alert-dismissible fade show <%= notice.present? ? 'alert-success' : 'alert-danger' %> <%= 'd-none' unless (alert || notice) %>" role="alert">
      <%= alert || notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="container content-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/secret_codes/_secret_code.html.erb
<tr>
	<td><%= secret_code.code %></td>
	<td><%= secret_code.user.present? ? secret_code.user.email : "-" %></td>
</tr>

app/views/secret_codes/create.js.erb
$("#secret_codes").prepend('<%= j render @secret_codes %>');

app/views/secret_codes/index.html.erb
<div class="row">
	<div class="col-md-6">
		<h2>Secret codes</h2>
	</div>
	<div class="col-md-6">
		<%= form_for(@secret_code, remote: true, html: { class: "d-inline-block float-right form-inline" }) do |f| %>
			How many?
			<%= f.select :number_of_codes, options_for_select( [1, 10, 20, 50, 100], 10), {}, {class: "form-control"}%>
			<%= f.submit "Generate Secret codes", data: { disable_with: "Generating..." }, class: "btn btn-primary" %>
		<% end %>
	</div>
</div>
<table class="table">
	<thead>
		<tr>
			<th>Secret Code</th>
			<th>Associated User</th>
		</tr>
	</thead>
	<tbody id="secret_codes">
		<%= render @secret_codes %>
	</tbody>
</table>
<%= will_paginate @secret_codes %>